### ISSUE TITLE
Can't preview a boxFile: DiskCookieStorage changing policy from 2 to 0

### ISSUE THREAD

**Issue by wangqiwei66** [box/box-ios-sdk#589] opened 2019-02-11 08:35 UTC
When I use appUser to preview a box file with ios-sdk 2.2.0, box present an error view with "not enough space":
<img width="327" alt="image" src="https://user-images.githubusercontent.com/23308747/52552343-c7f10680-2e1a-11e9-8f7a-6ab8ce2227b7.png">
logging this entering box: 
2019-02-11 16:18:26.009156+0800 SGMobile[9806:118304] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///Users/heping/Library/Developer/CoreSimulator/Devices/FE91D1DE-E14E-406D-8554-0812528AB3B1/data/Containers/Data/Application/8617ECB4-40BF-42BC-9F91-93D1026B2D7A/Library/Cookies/com.ibm.cio.be.soe.SolutionSeeker.binarycookies
exit the box window:
2019-02-11 16:28:45.979934+0800 SGMobile[9806:118304] DiskCookieStorage changing policy from 0 to 2, cookie file: file:///Users/heping/Library/Developer/CoreSimulator/Devices/FE91D1DE-E14E-406D-8554-0812528AB3B1/data/Containers/Data/Application/8617ECB4-40BF-42BC-9F91-93D1026B2D7A/Library/Cookies/com.ibm.cio.be.soe.SolutionSeeker.binarycookies
How could I avoid this warning and make an correct preview? Following is the code:
<img width="883" alt="image" src="https://user-images.githubusercontent.com/23308747/52552399-08508480-2e1b-11e9-9bf9-6827a1a91498.png">

**Comment by mattwiller** [comment] 2019-02-11 23:57
@wangqiwei66 This appears to be a duplicate of https://github.com/box/box-ios-preview-sdk/issues/49

Since this looks like an issue with the Preview SDK and not the base Content SDK, I'm going to close this issue — we'll go forward with the linked ticket in the Preview SDK repository.

**Closed as completed by mattwiller** 2019-02-11 23:57 UTC
