### ISSUE TITLE
[BOXFileThumbnailRequest performRequestWithProgress:completion:] always results in nil image

### ISSUE THREAD

**Issue by vinceplusplus** [box/box-ios-sdk#66] opened 2015-08-24 15:25 UTC
image in completion handler is always nil

**Comment by boxtcarpel** [comment] 2015-08-24 18:55
Hello Vince, thank you for using the SDK. How are you getting your BOXFileThumbnailRequest object? Are you using the BOXContentClient's -fileThumbnailRequestWithID:size: method?
If you haven't already, please compare against the sample app to find the expected usage.

Please let us know if that helps or if you are still encountering issues.

**Comment by vinceplusplus** [comment] 2015-08-25 00:50
Thanks, I have just tried the sample and it worked. It seems that the request must be retained until completion to have useful result, is it the intended practice?

**Comment by boxtcarpel** [comment] 2015-08-25 06:35
You shouldn't have to retain the request at the app layer. The sample app does it, but only in order to be able to cancel the request if the cell gets deallocated.

To test that, you can try changing line 66 in BOXSampleItemCell.m to 'BOXFileThumbnailRequest *request2 =' instead of self.request, and then call performRequest on request2. I made that change locally and I am still getting the thumbnails.

Do you see any other differences between your code and the sample app?

Hope this helps.

**Comment by vinceplusplus** [comment] 2015-08-26 01:46
I grabbed the zip download of the latest master branch, changed clientId and clientSecret, changed the two lines as you suggested, ran the app, navigated to a folder containing an image file, the app crashed with the following log:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* setObjectForKey: object cannot be nil (key: ***************************)'

I added Exception Breakpoint and tried again, it located the following line in BOXSampleThumbnailsHelper.m:
    [self.thumbnailCache setObject:thumbnail forKey:[self keyForItemID:itemID userID:userID]];

The following was the calling line in BOXSampleItemCell.m:
                        [thumbnailsHelper storeThumbnailForItemWithID:self.item.modelID userID:self.client.user.modelID thumbnail:image];

image showed nil as its value. Setting a nil object in a dictionary is obviously not allowed and thus caused the exception. Reverted the two lines then the app ran fine

**Comment by skathiresan** [comment] 2015-08-26 05:27
I am facing the same issue that @vinceplusplus  has mentioned.  
The image in the completionhandler is always nil.  This used to work just fine in the previous version.
It works if i have a strong property for the thumbnail request.   I am not sure if i want to have my class that way though.

**Comment by RicoYao** [comment] 2015-08-26 17:57
@boxtcarpel I believe this was caused by a recent change made by @achunBOX to eliminate the strong reference to the request from within the completion block:

https://github.com/box/box-ios-sdk/blob/master/BoxContentSDK/BoxContentSDK/Requests/BOXFileThumbnailRequest.m#L90

I believe we need to undo this, at least for this particular request.

**Comment by RicoYao** [comment] 2015-08-26 22:13
Created this pull request: https://github.com/box/box-ios-sdk/pull/75

**Comment by RicoYao** [comment] 2015-08-27 17:11
hey @vinceplusplus , @skathiresan I believe this should be fixed now but please re-open if you find otherwise. We'll probably increment the official version of this SDK pretty soon, but for now, just pull from the trunk.

**Closed as completed by RicoYao** 2015-08-27 17:11 UTC
