### ISSUE TITLE
ASWebAuthenticationSessionErrorCodeCanceledLogin not handled correctly

### ISSUE THREAD

**Issue by robertwijas** [box/box-ios-sdk#728] opened 2020-06-30 19:47 UTC
### Description of the Issue
After calling `BoxSDK.getOAuth2Client` If user cancels authentication the SDK returns `.invalidOAuthRedirectConfiguration` error.

This is where the info about the actual error is lost:
https://github.com/box/box-ios-sdk/blob/62f730aadccf75907ec304d58b773c2b19552a61/Sources/BoxSDK.swift#L360-L366

This makes it impossible to correctly handle cancellation.

### Steps to Reproduce
1. Start auth session on any platform using `ASWebAuthenticationSession`.
2. Tap Cancel.
3. SDK will return an error with no trace allowing you to detect that the original source is `ASWebAuthenticationSessionErrorCodeCanceledLogin`.

### Expected Behavior
The result should include enough information to recognize cancelling.

### Versions Used
iOS SDK: 4.0.0
iOS: 13.5
Xcode: 11.5

**Comment by sujaygarlanka** [comment] 2020-07-01 22:00
@robertwijas To clarify, you would like us to return the `error` variable within BoxAPIAuthError so you have more information regarding the cause of the error.

**Comment by robertwijas** [comment] 2020-07-02 05:50
@sujaygarlanka yes, that would solve the issue and it would also be consistent with how the SDK wraps errors in other places. Having a correct message (instead of always passing `invalidOAuthRedirectConfiguration`) would be a nice bonus 😃.

**Comment by sujaygarlanka** [comment] 2020-07-02 21:28
@robertwijas Going to return the error for now. Not currently changing the error message in order to avoid a breaking change. We will consider it in the future. We will be doing an iOS release soon after this PR is merged.

**Closed as completed by sujaygarlanka** 2020-07-02 21:28 UTC
Labels: bug
